In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../data/placement.csv")

In [3]:
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [4]:
df =df.iloc[0:,1:]

In [5]:
df

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

# Opening CSV file from an URL

In [ ]:
import requests
from io import StringIO

url = ""
headers={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/"}

req = requests.get(url, headers=headers)

data = StringIO(req.text)

df = pd.read_csv(data)
df

# Sep Parameter

In [ ]:
pd.read_csv("data.tsv", sep="\t")

# Index column

In [ ]:
pd.read_csv("data.csv" ,index_col="sno")

# Header Parameter

In [ ]:
pd.read_csv("test.csv", header=1)

# use_col parameter

In [6]:
import pandas as pd
pd.read_csv("../../data/placement.csv", usecols=["cgpa","placement"])

    cgpa  placement
0    6.8          1
1    5.9          0
2    5.3          0
3    7.4          1
4    5.8          0
..   ...        ...
95   4.3          0
96   4.4          0
97   6.7          1
98   6.3          1
99   6.2          1

[100 rows x 2 columns]

# Encoding Parameter

In [ ]:
pd.read_csv("zomato.csv", encoding="latin-1")

# skip bad lines

In [ ]:
pd.read_csv("BX_Books.csv", sep=";", encoding="latin-1", error_bad_lines=False)

# data type parameter

In [ ]:
pd.read_csv("data.csv", dtype={"target":int})

# Handling Dates

In [ ]:
pd.read_csv("IPL Matches 2008-2020.csv", parse_dates=["date"]).info()

# Convertors

In [7]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return name

In [ ]:
pd.read_csv("IPL Matches 2008-2020.csv", converters ={"team1":rename})

# na_values parameters

In [ ]:
pd.read_csv("data.csv", na_values=["n.a.","na","--"]) # values

# Loading a huge dataset in chunks

In [ ]:
dfs = pd.read_csv("data_fram.csv", chunksize=5000)

In [ ]:
for chunks in dfs:
    print(chunks.shape)